"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { useI18n } from "@/src/i18n/context";
import { Decimal } from "@/src/lib/decimal";
import { providerCostImpact, type BalancePosition } from "@/src/lib/payment-ledger/calculations";
import type { PaymentAccountType, PaymentEvent } from "@/src/lib/payment-ledger/types";

type Account = { id: number; name: string; providerName: string | null; accountType: PaymentAccountType; isActive: boolean };
type EventView = PaymentEvent & { impliedFx: string | null; fx: { expectedTargetAmount: string; variance: string } | null; expectedFee: string | null; feeVariance: string | null };
type Total = { assetCode: string; immediatelyAvailable: string; rollingReserve: string; fundsInTransit: string; totalOwned: string };
type Transit = { sourceEventId: number; sourceAccountId: number; destinationAccountId: number | null; sourceAssetCode: string; sourceAmount: string; outstandingAmount: string };
type ReserveLot = { id: number; paymentAccountId: number; assetCode: string; holdDate: string; amount: string; expectedReleaseDate: string | null; released: string; actualReleaseDate: string | null; outstanding: string };
type Tab = "accounts" | "transactions" | "balances" | "reserves" | "comparison";

export default function PaymentAccountsClient({ accounts, events, balances, totals, transit, reserveLots }: { accounts: Account[]; events: EventView[]; balances: BalancePosition[]; totals: Total[]; transit: Transit[]; reserveLots: ReserveLot[] }) {
  const { t: messages } = useI18n(); const t = messages.paymentAccounts; const router = useRouter();
  const [tab, setTab] = useState<Tab>("accounts"); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [selectedAccount, setSelectedAccount] = useState(accounts[0]?.id ?? 0); const fileRef = useRef<HTMLInputElement>(null);
  const accountName = (id: number | null) => accounts.find((account) => account.id === id)?.name ?? "—";

  async function submitJson(url: string, body: Record<string, unknown>, success: string) {
    setBusy(true); setNotice("");
    try { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(result.error || t.error); setNotice(success); router.refresh(); }
    catch (error) { setNotice(error instanceof Error ? error.message : t.error); } finally { setBusy(false); }
  }
  async function createAccount(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    await submitJson("/api/payment-accounts", { name: data.get("name"), providerName: data.get("provider"), accountType: data.get("type") }, t.accountCreated);
  }
  async function upload(file: File) {
    if (!selectedAccount) return; setBusy(true); setNotice(""); const form = new FormData(); form.append("file", file); form.append("paymentAccountId", String(selectedAccount));
    try { const response = await fetch("/api/payment-accounts/import", { method: "POST", body: form }); const result = await response.json().catch(() => ({})) as { error?: string; reused?: boolean }; if (!response.ok) throw new Error(result.error || t.error); setNotice(result.reused ? t.duplicate : t.imported); router.refresh(); }
    catch (error) { setNotice(error instanceof Error ? error.message : t.error); } finally { setBusy(false); }
  }
  const comparison = useMemo(() => accounts.map((account) => {
    const rows = events.filter((event) => event.paymentAccountId === account.id); const grouped = new Map<string, { source: string; target: string; volume: Decimal; expected: Decimal; actual: Decimal; feeVariance: Decimal; fxVariance: Decimal; expectedKnown: boolean; actualKnown: boolean; fxKnown: boolean }>();
    for (const event of rows) { const source = (event.sourceAssetCode ?? event.balanceAssetCode).toUpperCase(); const target = event.balanceAssetCode.toUpperCase(); const corridor = source === target ? source : `${source} → ${target}`; const item = grouped.get(corridor) ?? { source, target, volume: new Decimal(0), expected: new Decimal(0), actual: new Decimal(0), feeVariance: new Decimal(0), fxVariance: new Decimal(0), expectedKnown: false, actualKnown: false, fxKnown: false };
      if (event.sourceAmount) item.volume = item.volume.plus(event.sourceAmount); if (event.expectedFee && source === target) { item.expected = item.expected.plus(event.expectedFee); item.expectedKnown = true; } if (event.actualFeeAmount && event.actualFeeAssetCode?.toUpperCase() === target) { item.actual = item.actual.plus(event.actualFeeAmount); item.actualKnown = true; } if (event.feeVariance && source === target) item.feeVariance = item.feeVariance.plus(event.feeVariance); if (event.fx) { item.fxVariance = item.fxVariance.plus(event.fx.variance); item.fxKnown = true; } grouped.set(corridor, item); }
    return [...grouped].map(([corridor, item]) => { const cost = providerCostImpact(item.actualKnown ? item.actual.toFixed() : null, item.actualKnown ? item.target : null, item.fxKnown ? item.fxVariance.toFixed() : null, item.target); const reserve = balances.find((position) => position.paymentAccountId === account.id && position.assetCode === item.target)?.reserve ?? "0"; const inTransit = transit.filter((position) => position.sourceAccountId === account.id && position.sourceAssetCode === item.target).reduce((sum, position) => sum.plus(position.outstandingAmount), new Decimal(0)).toFixed(); return { account: account.name, corridor, volume: `${item.volume.toFixed()} ${item.source}`, expected: item.expectedKnown ? `${item.expected.toFixed()} ${item.target}` : null, actual: item.actualKnown ? `${item.actual.toFixed()} ${item.target}` : null, feeVariance: item.expectedKnown && item.actualKnown ? `${item.feeVariance.toFixed()} ${item.target}` : null, fxVariance: item.fxKnown ? `${item.fxVariance.toFixed()} ${item.target}` : null, providerCost: cost ? `${cost} ${item.target}` : null, reserve: `${reserve} ${item.target}`, inTransit: `${inTransit} ${item.target}` }; });
  }).flat(), [accounts, events, balances, transit]);

  return <div>
    <nav style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 18 }}><Link href="/reconciliation" style={topStyle(false)}>{t.topClientFunds}</Link><span style={topStyle(true)}>{t.topPayments}</span></nav>
    <h1 style={{ fontSize: 22, color: "#1e3a5f", margin: 0 }}>{t.title}</h1><p style={{ color: "#64748b", fontSize: 13, margin: "6px 0 18px" }}>{t.subtitle}</p>
    <div style={{ display: "flex", gap: 6, overflowX: "auto", paddingBottom: 8, marginBottom: 16 }}>{(["accounts", "transactions", "balances", "reserves", "comparison"] as Tab[]).map((name) => <button key={name} type="button" onClick={() => setTab(name)} style={tabStyle(tab === name)}>{t[name]}</button>)}</div>
    {notice && <div role="status" style={{ padding: 10, background: "#eff6ff", color: "#1e40af", borderRadius: 6, marginBottom: 14, fontSize: 13 }}>{notice}</div>}
    {tab === "accounts" && <div style={gridStyle}>
      <Card title={t.addAccount}><form onSubmit={createAccount} style={formStyle}><input required name="name" placeholder={t.accountName} style={inputStyle}/><input name="provider" placeholder={t.providerName} style={inputStyle}/><select name="type" style={inputStyle}>{["psp", "wallet", "exchange", "bank", "other"].map((type) => <option key={type}>{type}</option>)}</select><button disabled={busy} style={primaryStyle}>{t.create}</button></form></Card>
      <Card title={t.accounts}>{accounts.length === 0 ? <p>{t.noAccounts}</p> : accounts.map((account) => <div key={account.id} style={rowStyle}><strong>{account.name}</strong><span>{account.providerName ?? "—"} · {account.accountType}</span></div>)}</Card>
      {accounts.length > 0 && <Card title={t.saveAsset}><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void submitJson("/api/payment-accounts/assets", { paymentAccountId: Number(data.get("account")), assetCode: data.get("asset"), assetType: data.get("assetType"), openingAvailableBalance: data.get("available"), openingReserveBalance: data.get("reserve"), openingBalanceDate: data.get("date") }, t.saveAsset); }} style={formStyle}><AccountSelect accounts={accounts}/><input required name="asset" placeholder={t.asset} style={inputStyle}/><select name="assetType" style={inputStyle}><option value="fiat">{t.fiat}</option><option value="crypto">{t.crypto}</option></select><input required name="available" defaultValue="0" placeholder={t.openingAvailable} style={inputStyle}/><input required name="reserve" defaultValue="0" placeholder={t.openingReserve} style={inputStyle}/><input name="date" type="date" style={inputStyle}/><button disabled={busy} style={primaryStyle}>{t.saveAsset}</button></form></Card>}
      {accounts.length > 0 && <RuleForms accounts={accounts} submitJson={submitJson} busy={busy}/>}
    </div>}
    {tab === "transactions" && <><Card title={t.upload}><p style={{ color: "#64748b", fontSize: 13 }}>{accounts.length ? t.uploadHint : t.noAccounts}</p>{accounts.length > 0 && <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><select value={selectedAccount} onChange={(event) => setSelectedAccount(Number(event.target.value))} style={inputStyle}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select><input ref={fileRef} type="file" accept=".csv,.xlsx" hidden onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void upload(file); }}/><button disabled={busy} onClick={() => fileRef.current?.click()} style={primaryStyle}>{t.upload}</button></div>}</Card><DataTable headers={[t.eventDate, t.selectAccount, t.eventType, t.amount, t.source, t.actualFee, t.impliedFx]} rows={events.map((event) => [event.eventDate, accountName(event.paymentAccountId), event.eventType, `${event.balanceDirection} ${event.balanceAmount} ${event.balanceAssetCode}`, event.sourceAmount ? `${event.sourceAmount} ${event.sourceAssetCode}` : "—", event.actualFeeAmount ? `${event.actualFeeAmount} ${event.actualFeeAssetCode}` : "—", event.impliedFx ?? "—"])} empty={t.noTransactions}/></>}
    {tab === "balances" && <><div style={gridStyle}>{totals.map((total) => <Card key={total.assetCode} title={total.assetCode}><Metric label={t.immediatelyAvailable} value={total.immediatelyAvailable}/><Metric label={t.fundsInTransit} value={total.fundsInTransit}/><Metric label={t.rollingReserve} value={total.rollingReserve}/><Metric label={t.totalFunds} value={total.totalOwned}/></Card>)}</div><DataTable headers={[t.selectAccount, t.accountType, t.asset, t.calculatedAvailable, t.calculatedReserve, t.totalFunds, t.reportedBalance, t.difference]} rows={balances.map((balance) => [accountName(balance.paymentAccountId), accounts.find((account) => account.id === balance.paymentAccountId)?.accountType ?? "—", balance.assetCode, balance.available, balance.reserve, balance.totalOwned, balance.reportedAvailable ?? "—", balance.availableDifference ?? "—"])} empty={t.noTransactions}/>{transit.length > 0 && <DataTable headers={[t.selectAccount, t.asset, t.amount, t.outstanding]} rows={transit.map((item) => [accountName(item.sourceAccountId), item.sourceAssetCode, item.sourceAmount, item.outstandingAmount])} empty=""/>}</>}
    {tab === "reserves" && <><p style={{ color: "#64748b", fontSize: 13 }}>{t.exposureNote}</p><DataTable headers={[t.selectAccount, t.asset, t.eventDate, t.amount, t.expectedRelease, t.actualReleased, t.outstanding]} rows={reserveLots.map((lot) => [accountName(lot.paymentAccountId), lot.assetCode, lot.holdDate, lot.amount, lot.expectedReleaseDate ?? "—", lot.released, lot.outstanding])} empty={t.noTransactions}/></>}
    {tab === "comparison" && <><p style={{ color: "#64748b", fontSize: 13 }}>{t.exposureNote}</p><DataTable headers={[t.selectAccount, t.asset, t.source, t.expectedFee, t.actualFee, t.feeVariance, t.fxVariance, t.providerCost, t.fundsInTransit, t.rollingReserve]} rows={comparison.map((row) => [row.account, row.corridor, row.volume, row.expected ?? "—", row.actual ?? "—", row.feeVariance ?? "—", row.fxVariance ?? "—", row.providerCost ?? "—", row.inTransit, row.reserve])} empty={t.noTransactions}/></>}
  </div>;
}

function RuleForms({ accounts, submitJson, busy }: { accounts: Account[]; submitJson: (url: string, body: Record<string, unknown>, success: string) => Promise<void>; busy: boolean }) { const { t: messages } = useI18n(); const t = messages.paymentAccounts; return <>
  <Card title={t.expectedFee}><form style={formStyle} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void submitJson("/api/payment-accounts/rules", { kind: "fee", paymentAccountId: Number(data.get("account")), eventType: data.get("eventType"), assetCode: data.get("asset"), percentageRate: data.get("percentage"), fixedAmount: data.get("fixed"), fixedAssetCode: data.get("asset"), effectiveFrom: data.get("from") }, t.expectedFee); }}><AccountSelect accounts={accounts}/><select name="eventType" style={inputStyle}>{["deposit", "withdrawal", "refund", "chargeback", "fee", "settlement", "transfer", "conversion"].map((type) => <option key={type}>{type}</option>)}</select><input name="asset" placeholder={t.asset} style={inputStyle}/><input name="percentage" defaultValue="0" placeholder="%" style={inputStyle}/><input name="fixed" defaultValue="0" placeholder={t.fee} style={inputStyle}/><input required name="from" type="date" style={inputStyle}/><button disabled={busy} style={primaryStyle}>{t.expectedFee}</button></form></Card>
  <Card title={t.rollingReserve}><form style={formStyle} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void submitJson("/api/payment-accounts/rules", { kind: "reserve", paymentAccountId: Number(data.get("account")), assetCode: data.get("asset"), reservePercentage: data.get("percentage"), holdPeriodDays: Number(data.get("days")), effectiveFrom: data.get("from") }, t.rollingReserve); }}><AccountSelect accounts={accounts}/><input name="asset" placeholder={t.asset} style={inputStyle}/><input name="percentage" placeholder="%" style={inputStyle}/><input name="days" type="number" min="0" placeholder="Days" style={inputStyle}/><input required name="from" type="date" style={inputStyle}/><button disabled={busy} style={primaryStyle}>{t.rollingReserve}</button></form></Card>
  </>; }
function AccountSelect({ accounts }: { accounts: Account[] }) { return <select name="account" style={inputStyle}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select>; }
function Card({ title, children }: { title: string; children: ReactNode }) { return <section style={{ background: "#fff", border: "1px solid #e2e8f0", borderRadius: 8, padding: 16, marginBottom: 14 }}><h2 style={{ fontSize: 14, color: "#334155", margin: "0 0 12px" }}>{title}</h2>{children}</section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div style={rowStyle}><span>{label}</span><strong>{value}</strong></div>; }
function DataTable({ headers, rows, empty }: { headers: string[]; rows: string[][]; empty: string }) { if (!rows.length) return <Card title={empty || "—"}><span>—</span></Card>; return <div style={{ overflowX: "auto", background: "#fff", border: "1px solid #e2e8f0", borderRadius: 8, marginBottom: 16 }}><table style={{ width: "100%", borderCollapse: "collapse", minWidth: 720 }}><thead><tr>{headers.map((header) => <th key={header} style={cellStyle}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((value, column) => <td key={column} style={cellStyle}>{value}</td>)}</tr>)}</tbody></table></div>; }
const topStyle = (active: boolean) => ({ padding: "8px 12px", borderRadius: 6, textDecoration: "none", fontSize: 13, fontWeight: 600, color: active ? "#fff" : "#334155", background: active ? "#1e3a5f" : "#fff", border: "1px solid #cbd5e1" });
const tabStyle = (active: boolean) => ({ ...topStyle(active), cursor: "pointer", whiteSpace: "nowrap" as const });
const gridStyle = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 300px), 1fr))", gap: 14 };
const formStyle = { display: "flex", flexDirection: "column" as const, gap: 8 };
const inputStyle = { minHeight: 38, padding: "8px 10px", border: "1px solid #cbd5e1", borderRadius: 6, minWidth: 0, background: "#fff" };
const primaryStyle = { minHeight: 38, padding: "8px 12px", border: 0, borderRadius: 6, background: "#1e3a5f", color: "#fff", fontWeight: 600, cursor: "pointer" };
const rowStyle = { display: "flex", justifyContent: "space-between", gap: 12, padding: "8px 0", borderBottom: "1px solid #f1f5f9", fontSize: 13 };
const cellStyle = { padding: "10px 12px", borderBottom: "1px solid #e2e8f0", textAlign: "start" as const, fontSize: 12, whiteSpace: "nowrap" as const };
