"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { useI18n } from "@/src/i18n/context";
import { Decimal } from "@/src/lib/decimal";
import { calculateProcessedVolumeCorridors, providerCostImpact, type BalancePosition, type ProviderCostFacts } from "@/src/lib/payment-ledger/calculations";
import type { PaymentAccountType, PaymentEvent } from "@/src/lib/payment-ledger/types";
import { Alert, EmptyState } from "@/src/components/ui/feedback";
import { PageDescription, PageHeader, PageHeading, PageTitle } from "@/src/components/ui/page";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/src/components/ui/tabs";

type Account = { id: number; name: string; providerName: string | null; accountType: PaymentAccountType; clientFundsEligible: boolean; isActive: boolean };
type EventView = PaymentEvent & { impliedFx: string | null; fx: { expectedTargetAmount: string; variance: string } | null; costFacts: ProviderCostFacts };
type Total = { assetCode: string; immediatelyAvailable: string; rollingReserve: string; fundsInTransit: string; totalOwned: string };
type Transit = { sourceEventId: number; sourceAccountId: number; destinationAccountId: number | null; sourceAssetCode: string; sourceAmount: string; outstandingAmount: string };
type ReserveLot = { id: number; paymentAccountId: number; assetCode: string; holdDate: string; amount: string; expectedReleaseDate: string | null; released: string; actualReleaseDate: string | null; outstanding: string };
type UnlinkedReserveRelease = { id: number; paymentAccountId: number; assetCode: string; eventDate: string; amount: string; relatedProviderEventId: string | null };
type Tab = "accounts" | "transactions" | "balances" | "reserves" | "comparison";

export default function PaymentAccountsClient({ accounts, events, balances, totals, transit, reserveLots, unlinkedReserveReleases }: { accounts: Account[]; events: EventView[]; balances: BalancePosition[]; totals: Total[]; transit: Transit[]; reserveLots: ReserveLot[]; unlinkedReserveReleases: UnlinkedReserveRelease[] }) {
  const { t: messages } = useI18n(); const t = messages.paymentAccounts; const router = useRouter();
  const [tab, setTab] = useState<Tab>("accounts"); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [selectedAccount, setSelectedAccount] = useState(accounts[0]?.id ?? 0); const fileRef = useRef<HTMLInputElement>(null);
  const [newAccountType, setNewAccountType] = useState<PaymentAccountType>("psp"); const [newAccountEligible, setNewAccountEligible] = useState(true);
  const accountName = (id: number | null) => accounts.find((account) => account.id === id)?.name ?? "—";

  async function submitJson(url: string, body: Record<string, unknown>, success: string, method = "POST") {
    setBusy(true); setNotice("");
    try { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(result.error || t.error); setNotice(success); router.refresh(); }
    catch (error) { setNotice(error instanceof Error ? error.message : t.error); } finally { setBusy(false); }
  }
  async function createAccount(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    await submitJson("/api/payment-accounts", { name: data.get("name"), providerName: data.get("provider"), accountType: data.get("type"), clientFundsEligible: data.get("clientFundsEligible") === "on" }, t.accountCreated);
  }
  async function upload(file: File) {
    if (!selectedAccount) return; setBusy(true); setNotice(""); const form = new FormData(); form.append("file", file); form.append("paymentAccountId", String(selectedAccount));
    try { const response = await fetch("/api/payment-accounts/import", { method: "POST", body: form }); const result = await response.json().catch(() => ({})) as { error?: string; reused?: boolean; overlapWarning?: boolean }; if (!response.ok) throw new Error(result.error || t.error); setNotice(result.reused ? t.duplicate : result.overlapWarning ? t.overlapWarning : t.imported); router.refresh(); }
    catch (error) { setNotice(error instanceof Error ? error.message : t.error); } finally { setBusy(false); }
  }
  const comparison = useMemo(() => accounts.map((account) => {
    const rows = events.filter((event) => event.paymentAccountId === account.id); const grouped = new Map<string, { corridor: string; source: string; target: string; volume: Decimal; volumeKnown: boolean; expected: Decimal; actual: Decimal; feeVariance: Decimal; fxVariance: Decimal; expectedKnown: boolean; actualKnown: boolean; fxKnown: boolean }>();
    const ensure = (corridor: string, source: string, target: string) => { const key = `${corridor}|${target}`; let item = grouped.get(key); if (!item) { item = { corridor, source, target, volume: new Decimal(0), volumeKnown: false, expected: new Decimal(0), actual: new Decimal(0), feeVariance: new Decimal(0), fxVariance: new Decimal(0), expectedKnown: false, actualKnown: false, fxKnown: false }; grouped.set(key, item); } return item; };
    for (const volume of calculateProcessedVolumeCorridors(rows)) { const item = ensure(volume.corridor, volume.sourceAssetCode, volume.balanceAssetCode); item.volume = item.volume.plus(volume.volume); item.volumeKnown = true; }
    for (const event of rows) { const usesDestination = event.destinationAmount !== null && event.destinationAssetCode !== null; const source = (usesDestination ? event.balanceAssetCode : event.sourceAssetCode ?? event.balanceAssetCode).toUpperCase(); const target = (usesDestination ? event.destinationAssetCode! : event.balanceAssetCode).toUpperCase(); const corridor = source === target ? source : `${source} → ${target}`; const facts = event.costFacts;
      if (facts.expectedFee) { const item = ensure(corridor, source, facts.expectedFee.assetCode); item.expected = item.expected.plus(facts.expectedFee.amount); item.expectedKnown = true; }
      if (facts.actualFee) { const item = ensure(corridor, source, facts.actualFee.assetCode); item.actual = item.actual.plus(facts.actualFee.amount); item.actualKnown = true; }
      if (facts.feeVariance) { const item = ensure(corridor, source, facts.feeVariance.assetCode); item.feeVariance = item.feeVariance.plus(facts.feeVariance.amount); }
      if (facts.fxVariance) { const item = ensure(corridor, source, facts.fxVariance.assetCode); item.fxVariance = item.fxVariance.plus(facts.fxVariance.amount); item.fxKnown = true; }
    }
    return [...grouped.values()].map((item) => { const cost = providerCostImpact(item.actualKnown ? item.actual.toFixed() : null, item.actualKnown ? item.target : null, item.fxKnown ? item.fxVariance.toFixed() : null, item.target); const reserve = balances.find((position) => position.paymentAccountId === account.id && position.assetCode === item.target)?.reserve ?? "0"; const inTransit = transit.filter((position) => position.sourceAccountId === account.id && position.sourceAssetCode === item.target).reduce((sum, position) => sum.plus(position.outstandingAmount), new Decimal(0)).toFixed(); return { account: account.name, corridor: item.corridor, volume: item.volumeKnown ? `${item.volume.toFixed()} ${item.source}` : "—", expected: item.expectedKnown ? `${item.expected.toFixed()} ${item.target}` : null, actual: item.actualKnown ? `${item.actual.toFixed()} ${item.target}` : null, feeVariance: item.expectedKnown && item.actualKnown ? `${item.feeVariance.toFixed()} ${item.target}` : null, fxVariance: item.fxKnown ? `${item.fxVariance.toFixed()} ${item.target}` : null, providerCost: cost ? `${cost} ${item.target}` : null, reserve: `${reserve} ${item.target}`, inTransit: `${inTransit} ${item.target}` }; });
  }).flat(), [accounts, events, balances, transit]);

  return <div className="payment-accounts-page">
    <nav className="business-section-nav"><Link href="/reconciliation" className="ui-button ui-button-secondary">{t.topClientFunds}</Link><span className="ui-button">{t.topPayments}</span></nav>
    <PageHeader><PageHeading><PageTitle>{t.title}</PageTitle><PageDescription>{t.subtitle}</PageDescription></PageHeading></PageHeader>
    <Tabs>
      <TabsList>{(["accounts", "transactions", "balances", "reserves", "comparison"] as Tab[]).map((name) => <TabsTrigger key={name} active={tab === name} onClick={() => setTab(name)}>{t[name]}</TabsTrigger>)}</TabsList>
      {notice && <Alert className="mt-4">{notice}</Alert>}
    {tab === "accounts" && <TabsContent><div className="business-card-grid">
      <Card title={t.addAccount}><form onSubmit={createAccount} style={formStyle}><input required name="name" placeholder={t.accountName} style={inputStyle}/><input name="provider" placeholder={t.providerName} style={inputStyle}/><select name="type" value={newAccountType} onChange={(event) => { const type = event.target.value as PaymentAccountType; setNewAccountType(type); setNewAccountEligible(type === "psp"); }} style={inputStyle}>{(["psp", "wallet", "exchange", "bank", "other"] as PaymentAccountType[]).map((type) => <option key={type} value={type}>{t.accountTypeLabels[type]}</option>)}</select><label style={{ fontSize: 13 }}><input name="clientFundsEligible" type="checkbox" checked={newAccountEligible} onChange={(event) => setNewAccountEligible(event.target.checked)}/> {t.clientFundsEligible}</label><button disabled={busy} style={primaryStyle}>{t.create}</button></form></Card>
      <Card title={t.accounts}>{accounts.length === 0 ? <p>{t.noAccounts}</p> : accounts.map((account) => <div key={account.id} style={rowStyle}><strong>{account.name}</strong><span>{account.providerName ?? "—"} · {t.accountTypeLabels[account.accountType]}</span><label style={{ fontSize: 12 }}><input type="checkbox" checked={account.clientFundsEligible} onChange={(event) => void submitJson("/api/payment-accounts", { paymentAccountId: account.id, clientFundsEligible: event.target.checked }, t.saveAsset, "PATCH")}/> {t.clientFundsEligible}</label></div>)}</Card>
      {accounts.length > 0 && <Card title={t.saveAsset}><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void submitJson("/api/payment-accounts/assets", { paymentAccountId: Number(data.get("account")), assetCode: data.get("asset"), assetType: data.get("assetType"), openingAvailableBalance: data.get("available"), openingReserveBalance: data.get("reserve"), openingBalanceDate: data.get("date") }, t.saveAsset); }} style={formStyle}><AccountSelect accounts={accounts}/><input required name="asset" placeholder={t.asset} style={inputStyle}/><select name="assetType" style={inputStyle}><option value="fiat">{t.fiat}</option><option value="crypto">{t.crypto}</option></select><input required name="available" defaultValue="0" placeholder={t.openingAvailable} style={inputStyle}/><input required name="reserve" defaultValue="0" placeholder={t.openingReserve} style={inputStyle}/><input name="date" type="date" style={inputStyle}/><button disabled={busy} style={primaryStyle}>{t.saveAsset}</button></form></Card>}
      {accounts.length > 0 && <RuleForms accounts={accounts} submitJson={submitJson} busy={busy}/>}
    </div></TabsContent>}
    {tab === "transactions" && <TabsContent><Card title={t.upload}><p className="business-page-copy">{accounts.length ? t.uploadHint : t.noAccounts}</p>{accounts.length > 0 && <div className="business-action-row"><select value={selectedAccount} onChange={(event) => setSelectedAccount(Number(event.target.value))} style={inputStyle}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select><input ref={fileRef} type="file" accept=".csv,.xlsx" hidden onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void upload(file); }}/><button disabled={busy} onClick={() => fileRef.current?.click()} style={primaryStyle}>{t.upload}</button></div>}</Card><DataTable headers={[t.eventDate, t.selectAccount, t.providerEventId, t.relatedProviderEventId, t.eventType, t.amount, t.source, t.actualFee, t.impliedFx]} rows={events.map((event) => [event.eventDate, accountName(event.paymentAccountId), event.providerEventId ?? "—", event.relatedProviderEventId ?? "—", t.eventTypeLabels[event.eventType], `${t.directionLabels[event.balanceDirection]} ${event.balanceAmount} ${event.balanceAssetCode}`, event.sourceAmount ? `${event.sourceAmount} ${event.sourceAssetCode}` : "—", event.costFacts.actualFee ? `${event.costFacts.actualFee.amount} ${event.costFacts.actualFee.assetCode}` : "—", event.impliedFx ?? "—"])} empty={t.noTransactions}/></TabsContent>}
    {tab === "balances" && <TabsContent><div className="business-card-grid">{totals.map((total) => <Card key={total.assetCode} title={total.assetCode}><Metric label={t.immediatelyAvailable} value={total.immediatelyAvailable}/><Metric label={t.fundsInTransit} value={total.fundsInTransit}/><Metric label={t.rollingReserve} value={total.rollingReserve}/><Metric label={t.totalFunds} value={total.totalOwned}/></Card>)}</div><DataTable headers={[t.selectAccount, t.accountType, t.asset, t.currentCalculatedAvailable, t.calculatedReserve, t.totalFunds, t.calculatedAtReported, t.reportedBalance, t.reportedAsOf, t.difference]} rows={balances.map((balance) => [accountName(balance.paymentAccountId), (() => { const type = accounts.find((account) => account.id === balance.paymentAccountId)?.accountType; return type ? t.accountTypeLabels[type] : "—"; })(), balance.assetCode, balance.available, balance.reserve, balance.totalOwned, balance.calculatedAvailableAtReported ?? "—", balance.reportedAvailable ?? "—", balance.reportedAsOf?.slice(0, 10) ?? "—", balance.availableDifference ?? "—"])} empty={t.noTransactions}/>{transit.length > 0 && <DataTable headers={[t.selectAccount, t.asset, t.amount, t.outstanding]} rows={transit.map((item) => [accountName(item.sourceAccountId), item.sourceAssetCode, item.sourceAmount, item.outstandingAmount])} empty=""/>}</TabsContent>}
    {tab === "reserves" && <TabsContent><p className="business-page-copy">{t.exposureNote}</p><DataTable headers={[t.selectAccount, t.asset, t.eventDate, t.amount, t.expectedRelease, t.actualReleased, t.actualReleaseDate, t.outstanding]} rows={reserveLots.map((lot) => [accountName(lot.paymentAccountId), lot.assetCode, lot.holdDate, lot.amount, lot.expectedReleaseDate ?? "—", lot.released, lot.actualReleaseDate ?? "—", lot.outstanding])} empty={t.noTransactions}/>{unlinkedReserveReleases.length > 0 && <><Alert tone="warning" className="mb-3">{t.unlinkedReleases}</Alert><DataTable headers={[t.selectAccount, t.asset, t.eventDate, t.amount, t.relatedProviderEventId]} rows={unlinkedReserveReleases.map((release) => [accountName(release.paymentAccountId), release.assetCode, release.eventDate, release.amount, release.relatedProviderEventId ?? "—"])} empty=""/></>}</TabsContent>}
    {tab === "comparison" && <TabsContent><p className="business-page-copy">{t.exposureNote}</p><DataTable headers={[t.selectAccount, t.asset, t.source, t.expectedFee, t.actualFee, t.feeVariance, t.fxVariance, t.providerCost, t.fundsInTransit, t.rollingReserve]} rows={comparison.map((row) => [row.account, row.corridor, row.volume, row.expected ?? "—", row.actual ?? "—", row.feeVariance ?? "—", row.fxVariance ?? "—", row.providerCost ?? "—", row.inTransit, row.reserve])} empty={t.noTransactions}/></TabsContent>}
    </Tabs>
  </div>;
}

function RuleForms({ accounts, submitJson, busy }: { accounts: Account[]; submitJson: (url: string, body: Record<string, unknown>, success: string) => Promise<void>; busy: boolean }) { const { t: messages } = useI18n(); const t = messages.paymentAccounts; return <>
  <Card title={t.expectedFee}><form style={formStyle} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void submitJson("/api/payment-accounts/rules", { kind: "fee", paymentAccountId: Number(data.get("account")), eventType: data.get("eventType"), feeBasis: data.get("feeBasis"), assetCode: data.get("asset"), feeAssetCode: data.get("feeAsset"), percentageRate: data.get("percentage"), fixedAmount: data.get("fixed"), effectiveFrom: data.get("from"), effectiveTo: data.get("to") }, t.expectedFee); }}><AccountSelect accounts={accounts}/><select name="eventType" style={inputStyle}>{(["deposit", "withdrawal", "refund", "chargeback", "fee", "settlement", "transfer", "conversion"] as const).map((type) => <option key={type} value={type}>{t.eventTypeLabels[type]}</option>)}</select><select name="feeBasis" style={inputStyle}><option value="source_amount">{t.sourceAmountBasis}</option><option value="balance_amount">{t.balanceAmountBasis}</option></select><input name="asset" placeholder={t.basisAssetOptional} style={inputStyle}/><input required name="feeAsset" placeholder={t.feeAsset} style={inputStyle}/><input name="percentage" defaultValue="0" placeholder="%" style={inputStyle}/><input name="fixed" defaultValue="0" placeholder={t.fee} style={inputStyle}/><input required name="from" type="date" style={inputStyle}/><input name="to" type="date" style={inputStyle}/><button disabled={busy} style={primaryStyle}>{t.expectedFee}</button></form></Card>
  <Card title={t.rollingReserve}><form style={formStyle} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void submitJson("/api/payment-accounts/rules", { kind: "reserve", paymentAccountId: Number(data.get("account")), assetCode: data.get("asset"), reservePercentage: data.get("percentage"), holdPeriodDays: Number(data.get("days")), effectiveFrom: data.get("from") }, t.rollingReserve); }}><AccountSelect accounts={accounts}/><input name="asset" placeholder={t.asset} style={inputStyle}/><input name="percentage" placeholder="%" style={inputStyle}/><input name="days" type="number" min="0" placeholder={t.days} style={inputStyle}/><input required name="from" type="date" style={inputStyle}/><button disabled={busy} style={primaryStyle}>{t.rollingReserve}</button></form></Card>
  </>; }
function AccountSelect({ accounts }: { accounts: Account[] }) { return <select name="account" style={inputStyle}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select>; }
function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="ui-card business-card"><h2 className="business-card-title">{title}</h2>{children}</section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="business-metric-row"><span>{label}</span><strong>{value}</strong></div>; }
function DataTable({ headers, rows, empty }: { headers: string[]; rows: string[][]; empty: string }) { if (!rows.length) return <EmptyState className="mb-4">{empty || "—"}</EmptyState>; return <div className="ui-table-shell business-data-table"><div className="ui-table-scroll"><table className="ui-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((value, column) => <td key={column}>{value}</td>)}</tr>)}</tbody></table></div></div>; }
const formStyle = { display: "flex", flexDirection: "column" as const, gap: 8 };
const inputStyle = { minHeight: 38, padding: "8px 10px", border: "1px solid #cbd5e1", borderRadius: 6, minWidth: 0, background: "#fff" };
const primaryStyle = { minHeight: 38, padding: "8px 12px", border: 0, borderRadius: 6, background: "#1e3a5f", color: "#fff", fontWeight: 600, cursor: "pointer" };
const rowStyle = { display: "flex", justifyContent: "space-between", gap: 12, padding: "8px 0", borderBottom: "1px solid var(--border-subtle)", fontSize: 13 };
